### ISSUE TITLE
Sync retrieval endpoint does not apply default event types

### ISSUE THREAD

**Issue by Patent2net** [jdp1ps/svp-harvester#147]
Try this to get blocked.
http://13.51.241.83/api/v1/references?history_safe_mode=false&identifiers_safe_mode=false&harvesters=hal&harvesters=idref&idref=122796527&orcid=0000-0003-2071-6594

**Comment by jdp1ps** [comment]
Event types default to None instead of "all" when parameters is omitted from sync retrieval request. 
Adding : `&events=created&events=updated&events=deleted&events=unchanged` to the request parameters solves the issue but should not be necessary.
`http://13.51.241.83/api/v1/references?history_safe_mode=false&identifiers_safe_mode=false&events=created&events=updated&events=deleted&events=unchanged&harvesters=hal&harvesters=idref&idref=122796527&orcid=0000-0003-2071-6594`

**Comment by jdp1ps** [comment]
The first request with defaults events (created, updated, deleted) returns results, but the subsequent requests don't. It is the normal behavior. Issue closed.
